### ISSUE TITLE
Submitting PRs after accidental deletion

### ISSUE THREAD

**Issue by nielstron** [nielstron/pyfronius#1]
Hey everyone, I accidentally deleted this repository... 

So all fork relationships are lost. If you want to submit a PR from a fork before the deletion, fork this repository, copy your changes over from the old fork, and place a PR. Sorry for the inconveniences!

 @farmio

**Comment by farmio** [comment]
Oops 🙃
I think the PR I had open isn't that important (Error things) and I don't really recall the discussion about it 😬

Could you do a release to pypi from current dev so the Ohmpilot stuff can be used from HA?

**Comment by nielstron** [comment]
I just invited you to collaborate on this repository (long due anyways and I don't have much time the last days :)

**Comment by farmio** [comment]
Thank you very much!
