### ISSUE TITLE
Cloud interface

### ISSUE THREAD

**Issue by drc38** [nielstron/pyfronius#10]
Hi, I have 1 fronius inverter on my home assistant network and another that is remote. I was hoping to connect both to HA using the one integration. Are there any plans to add the solar web api to this python bridge repo? I could not find much already on github relating to the fronius solar web api other than this repo in Go that can use either interface https://github.com/tgulacsi/fronius.

**Comment by nielstron** [comment]
There are no plans, but anyone is welcome to contribute something like this :)

**Comment by drc38** [comment]
I've had a go at an initial interface, but then realised getting a solar.web api account is not supported in my country so have no way  of testing it :( 
https://github.com/drc38/python-fronius-web

If it works then it shouldn't be too difficult to incorporate.

**Comment by drc38** [comment]
Fronius have now enabled api access for me so when I am able to clone your repo I'll submit a PR to incorporate the cloud api

**Comment by drc38** [comment]
An initial HACS integration for cloud polling of the Fronius is available here https://github.com/drc38/Fronius_solarweb
