### ISSUE TITLE
Cloning issue

### ISSUE THREAD

**Issue by drc38** [nielstron/pyfronius#11]
Hi, when I try to clone the repo I am getting the following errors
```
error: invalid path 'pyfronius/tests/test_structure/v0/solar_api/GetInverterRealtimeData.cgi?Scope=Device&DeviceIndex=1&DataCollection=CommonInverterData'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'
```
Using the suggested git restore gives the same error, any ideas?
```
error: invalid path 'pyfronius/tests/test_structure/v0/solar_api/GetInverterRealtimeData.cgi?Scope=Device&DeviceIndex=1&DataCollection=CommonInverterData'
```

**Comment by nielstron** [comment]
Are you using Windows? I have embedded some HTML files in the repository for testing purposes and these have illegal identifiers on Windows machines. Not quite sure how to remediate that.

**Comment by drc38** [comment]
I am using windows. Could they be added to .gitignore?

**Comment by drc38** [comment]
This appears to have worked around it `git config --global core.protectNTFS false` in Windows
