### ISSUE TITLE
Simple example...

### ISSUE THREAD

**Issue by ThomasRgbg** [nielstron/pyfronius#20]
Hi, 

thanks a lot for this great project. Seems to connect to my Symo Gen24+SmartMeter TS 65A-3 and the example.py returns tons of interesting values. 

However and sorry for my beginners question... :)

How would a very simple example code look like, when I just want to read one parameter (e.g. P_PV of system power flow) ? 

Regards, Thomas

**Comment by nielstron** [comment]
Hi Thomas,

a call to `fetch` returns a dict with the full current information about the PV system. If you only want to read a part of it, access this dict like a normal python dictionary (i.e. `res["P_PV"]`).

There is no way to only fetch specific values from a fronius device, but that should also not be necessary.

**Comment by ThomasRgbg** [comment]
Hi Niels, 

sorry If I'm getting confused. 

If I call 

`res = await fronius.fetch(power_flow=True, system_meter=False, system_inverter=False, device_meter=[], device_storage=[], device_inverter=[], loop=loop)
`
I get 

`[{'timestamp': {'value': '2020-11-22T20:23:01+00:00'}, 'status': {'Code': 0, 'Reason': '', 'UserMessage': ''}, 'battery_mode': {'value': 'normal'}, 'state_of_charge': {'value': 78.19999694824219, 'unit': '%'}, 'battery_standby': {'value': False}, 'energy_day': {'value': None, 'unit': 'Wh'}, 'energy_total': {'value': None, 'unit': 'Wh'}, 'energy_year': {'value': None, 'unit': 'Wh'}, 'meter_location': {'value': 'grid'}, 'meter_mode': {'value': 'bidirectional'}, 'power_battery': {'value': 3428.7509765625, 'unit': 'W'}, 'power_grid': {'value': 3.8, 'unit': 'W'}, 'power_load': {'value': -3311.8, 'unit': 'W'}, 'power_photovoltaics': {'value': 6.333533763885498, 'unit': 'W'}, 'relative_autonomy': {'value': 99.88525877166495, 'unit': '%'}, 'relative_self_consumption': {'value': 100.0, 'unit': '%'}}]`

So for the parameter itself, e.g. P_PV/power_photovoltaics the dictionary works. 

But fetch itself returns a list, so I would need to do something like

`res[0]['power_photovoltaics']['value']`

Is there a better way to address this entry in the list?

**Comment by nielstron** [comment]
There are some built in, more specific functions like `fronius.current_power_flow()`. Feel free to have a look at them :) But they'll always return a dictionary of some kind.
