### ISSUE TITLE
need better error handling

### ISSUE THREAD

**Issue by phsdv** [nielstron/pyfronius#3]
The Fronius inverter does not always return a Body,  if a module does not exists like for example the storage module. Hence the following line could trow an exception: 
`data = res['Body']['Data'] # shortcut` 
My proposal would be to add the following code after each _fetch_json():
```
        errcode = res['Head']['Status']['Code']
        errmsg = res['Head']['Status']['Reason']
        _LOGGER.debug("Error {} - {}".format(errcode, errmsg))
        if errcode == 255:
            return {}
``` 
Error 255 is the code that is returned when a module does not supported. Like this:
```
DEBUG:pyfronius:Error 255 - Storages are not supported
DEBUG:pyfronius:{}
```
Of course an other return than an empty dictionary is also possible, maybe a nice message to HA would be better.

**Comment by gbeine** [comment]
Hm, according to the Fronius Specification the Body is always there - but it may be that ```Data``` is empty.
```
   "Body" : {
      "Data" : {}
   },
```
That happens if a device is not enabled or does not exist.
As this is not an exception but covered by the API it should not be changed.
The status and the reason for it are given back to the caller in the sensor dict.

I'll change the API so that the sensor dict is returned in case ```Data``` is empty.

**Comment by phsdv** [comment]
I agree, probably `Data` did not exists.

**Comment by phsdv** [comment]
Maybe there is bug in the Fronius implementation as it really does not retrun a Body. As you can see in the 2nd debug line, there is no body, only a head with the status inside the head. In the end the exception trown is a `KeyError: 'Body'`
```
DEBUG:pyfronius:{'timestamp': {'value': '2018-01-07T08:50:47+01:00'}, 'status': {'Code': 0, 'Reason': '', 'UserMessage': ''}}
DEBUG:pyfronius:{'Head': {'RequestArguments': {'Scope': 'Device', 'DeviceClass': 'Meter', 'DeviceId': '0'}, 'Timestamp': '2018-01-07T08:50:48+01:00', 'Status': {'Code': 255, 'Reason': 'Meter 0 does not exist', 'UserMessage': ''}}}
Traceback (most recent call last):
  File "example.py", line 39, in <module>
    loop.run_until_complete(main(loop, "192.168.1.11"))
  File "/usr/lib/python3.5/asyncio/base_events.py", line 466, in run_until_complete
    return future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 293, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "example.py", line 22, in main
    res = yield from fronius.current_meter_data()
  File "/home/pi/computer/python/fronius/pyfronius/pyfronius/__init__.py", line 185, in current_meter_data
    if not res['Body']['Data']:
KeyError: 'Body'
```
so the new code `if not res['Body']['Data']:` does not work
Changing it the line to `if not 'Body' in res:` the code works without issue for me

**Comment by gbeine** [comment]
Now, the module takes care for both cases:
https://github.com/nielstron/pyfronius/blob/master/pyfronius/__init__.py#L68
