### ISSUE TITLE
No meter entities & errors about "No data returned"

### ISSUE THREAD

**Issue by ianleeder** [nielstron/pyfronius#30]
I'm sure this is a config error and not a bug, but appreciate if you could point out my idiocy for me.

Home Assistant recently updated to provide Energy monitoring.  I've had Fronius configured in there for a while, but never really looked too closely at which sensor was telling what.  Now I want to configure the Energy page, and it seems I am not receiving meter data from my Fronius.  Yes, I have a smart meter 63A installed...

My configuration looks like this:
```
sensor:
  - platform: fronius
    resource: http://192.168.x.x
    scan_interval: 10
    monitored_conditions:
    - sensor_type: inverter
      device: 1
    - sensor_type: meter
      scope: system
    - sensor_type: power_flow
```
I can't find a version specific to pyfronius, but I'm running latest HA `core-2021.8.6`.

I have confirmed the following API calls all work and return data:
```
/solar_api/v1/GetInverterRealtimeData.cgi?Scope=Device&DeviceId=1&DataCollection=CommonInverterData
/solar_api/v1/GetMeterRealtimeData.cgi?Scope=System
/solar_api/v1/GetPowerFlowRealtimeData.fcgi
```

I can see entities created for my inverter, and my power_flow.  But the only `meter` entity I get is the timestamp sensor `sensor.timestamp_fronius_meter_system_http...`.  None of the other data nodes returned by `/solar_api/v1/GetMeterRealtimeData.cgi?Scope=System` get created.

Confusingly though, the errors getting logged are:
```
2021-08-15 21:24:32 INFO (SyncWorker_5) [root] Sending handshake.
2021-08-15 21:24:40 INFO (MainThread) [pyfronius] No data returned from {<API_VERSION.V0: 0>: 'GetInverterRealtimeData.cgi?Scope=Device&DeviceIndex={}&DataCollection=CommonInverterData', <API_VERSION.V1: 1>: 'GetInverterRealtimeData.cgi?Scope=Device&DeviceId={}&DataCollection=CommonInverterData'}
2021-08-15 21:24:42 INFO (SyncWorker_4) [root] Sending handshake.
2021-08-15 21:24:50 INFO (MainThread) [pyfronius] No data returned from {<API_VERSION.V0: 0>: 'GetInverterRealtimeData.cgi?Scope=Device&DeviceIndex={}&DataCollection=CommonInverterData', <API_VERSION.V1: 1>: 'GetInverterRealtimeData.cgi?Scope=Device&DeviceId={}&DataCollection=CommonInverterData'}
```
Which have the URL for the inverter, not the meter.  I have inverter data being returned just fine.

Any hints?

**Comment by ianleeder** [comment]
As usual when being 100% thorough before posting, I managed to work out a solution myself.  But I still wanted to post to get your opinion on it.

Apparently it works if I configure my meter as
```
    - sensor_type: meter
      device: 1
```

Using `scope: system` did not detect the data correctly.  Perhaps there is a bug after all?

For reference, here is the results of the two different API calls
### /solar_api/v1/GetMeterRealtimeData.cgi?Scope=System
```
{
   "Body" : {
      "Data" : {
         "1" : {
            "Current_AC_Phase_1" : 5.1920000000000002,
            "Current_AC_Sum" : 5.1920000000000002,
            "Details" : {
               "Manufacturer" : "Fronius",
               "Model" : "Smart Meter 63A-1",
               "Serial" : "18037887"
            },
            "Enable" : 1,
            "EnergyReactive_VArAC_Phase_1_Consumed" : 11762570,
            "EnergyReactive_VArAC_Phase_1_Produced" : 75958990,
            "EnergyReactive_VArAC_Sum_Consumed" : 11762570,
            "EnergyReactive_VArAC_Sum_Produced" : 75958990,
            "EnergyReal_WAC_Minus_Absolute" : 9841262,
            "EnergyReal_WAC_Phase_1_Consumed" : 18351860,
            "EnergyReal_WAC_Phase_1_Produced" : 9841262,
            "EnergyReal_WAC_Plus_Absolute" : 18351860,
            "EnergyReal_WAC_Sum_Consumed" : 18351860,
            "EnergyReal_WAC_Sum_Produced" : 9841262,
            "Frequency_Phase_Average" : 50,
            "Meter_Location_Current" : 0,
            "PowerApparent_S_Phase_1" : 1273.5899999999999,
            "PowerApparent_S_Sum" : 1273.5899999999999,
            "PowerFactor_Phase_1" : 0.95999999999999996,
            "PowerFactor_Sum" : 0.95999999999999996,
            "PowerReactive_Q_Phase_1" : -296.56999999999999,
            "PowerReactive_Q_Sum" : -296.56999999999999,
            "PowerReal_P_Phase_1" : 1224.96,
            "PowerReal_P_Sum" : 1224.96,
            "TimeStamp" : 1629026733,
            "Visible" : 1,
            "Voltage_AC_Phase_1" : 245.30000000000001
         }
      }
   },
   "Head" : {
      "RequestArguments" : {
         "DeviceClass" : "Meter",
         "Scope" : "System"
      },
      "Status" : {
         "Code" : 0,
         "Reason" : "",
         "UserMessage" : ""
      },
      "Timestamp" : "2021-08-15T21:25:34+10:00"
   }
}
```
### /solar_api/v1/GetMeterRealtimeData.cgi?Scope=Device&DeviceId=1
```
{
   "Body" : {
      "Data" : {
         "Current_AC_Phase_1" : 4.8280000000000003,
         "Current_AC_Sum" : 4.8280000000000003,
         "Details" : {
            "Manufacturer" : "Fronius",
            "Model" : "Smart Meter 63A-1",
            "Serial" : "18037887"
         },
         "Enable" : 1,
         "EnergyReactive_VArAC_Phase_1_Consumed" : 11762570,
         "EnergyReactive_VArAC_Phase_1_Produced" : 75958520,
         "EnergyReactive_VArAC_Sum_Consumed" : 11762570,
         "EnergyReactive_VArAC_Sum_Produced" : 75958520,
         "EnergyReal_WAC_Minus_Absolute" : 9841262,
         "EnergyReal_WAC_Phase_1_Consumed" : 18351677,
         "EnergyReal_WAC_Phase_1_Produced" : 9841262,
         "EnergyReal_WAC_Plus_Absolute" : 18351677,
         "EnergyReal_WAC_Sum_Consumed" : 18351677,
         "EnergyReal_WAC_Sum_Produced" : 9841262,
         "Frequency_Phase_Average" : 50,
         "Meter_Location_Current" : 0,
         "PowerApparent_S_Phase_1" : 1171.27,
         "PowerApparent_S_Sum" : 1171.27,
         "PowerFactor_Phase_1" : 0.93000000000000005,
         "PowerFactor_Sum" : 0.93000000000000005,
         "PowerReactive_Q_Phase_1" : -369.19999999999999,
         "PowerReactive_Q_Sum" : -369.19999999999999,
         "PowerReal_P_Phase_1" : 1094.73,
         "PowerReal_P_Sum" : 1094.73,
         "TimeStamp" : 1629026185,
         "Visible" : 1,
         "Voltage_AC_Phase_1" : 242.59999999999999
      }
   },
   "Head" : {
      "RequestArguments" : {
         "DeviceClass" : "Meter",
         "DeviceId" : "1",
         "Scope" : "Device"
      },
      "Status" : {
         "Code" : 0,
         "Reason" : "",
         "UserMessage" : ""
      },
      "Timestamp" : "2021-08-15T21:16:26+10:00"
   }
}
```

I still get the following error being logged:
```
2021-08-15 22:07:09 INFO (MainThread) [pyfronius] No data returned from {<API_VERSION.V0: 0>: 'GetInverterRealtimeData.cgi?Scope=Device&DeviceIndex={}&DataCollection=CommonInverterData', <API_VERSION.V1: 1>: 'GetInverterRealtimeData.cgi?Scope=Device&DeviceId={}&DataCollection=CommonInverterData'}
```
But it doesn't seem to prevent anything from working.  Anything I can do about that?

**Comment by nielstron** [comment]
Yeah, check #57047 for more insights on the configuration struggles :)

The error you posted is not an error. It is an artifact of the pyfronius package trying API version 0 on the inverter (which fails "no data returned")

**Comment by ianleeder** [comment]
Thanks man.  Appreciate you looking at it.

My system is working well enough for me, so my concern here is purely for the code.  Shouldn't the meter `scope: system` work?  When I call the API directly, the data is returned.  Seems that either the package is not forming the URL correctly, or not parsing the result correctly (I'm not too good with reading/debugging Python).

And I noticed the API version 0 in the log message, but it _also_ says API version 1 on the same line.  So my concern is two parts:
- Since the package dynamically determines which API version to use, why is it trying v0 at all
- Why is it logging no data returned for v1?

Side question, can you format the URL in the log with the device ID?  Having the braces {} in there makes it seem like the URL is invalid, and harder to debug.

Anyway, that's just my 2 cents.  If you want to drop this, I will.

**Comment by ianleeder** [comment]
Sorry, not sure if I need to tag you @nielstron after issue has been closed.

**Comment by nielstron** [comment]
You are right there are a few things that could be coded better, I will definitely have a look into them.

First, the "No data returned" issue actually seems quite odd to me right now. I think there *is* an issue parsing the scope system data (specifically in that it does not parse it at all rather than returning a list of all installed devices). You will notice that calling the URL returns data but manually pointing the fetch call to the URL returns nothing.

Secondly, I should definitely look into how to make the debugging info for no data returned more consise. Currently it does not contain the queried device as you correctly pointed out.

BTW by construction, to determine the API version supported, v0 has to be tried first. However this is actually not an issue here.

**Comment by ianleeder** [comment]
@nielstron If I get a chance tonight I might look at cloning this repo and setting up a local python env, to see if I can help out with anything.  Other than that, I think I saw elsewhere that you don't actually have a Fronius to test against?!  If you need to confirm any tests against a real device, ping me and I can help out.

**Comment by nielstron** [comment]
Could you please check with your fronius device what the following call returns?
Replace in `example.py` the call to fetch with a call to `current_system_meter_data` and print the result.
Looking at the code and tests, there should not be "no data" but rather the data of your device number 1 and the timestamps and status.

Please also let me know what is returned at night, when there is no production, and what is returned during the day.

**Comment by ianleeder** [comment]
Calling `current_system_meter_data` only prints
```
timestamp
status
meters
```

The variable `res` contains the following (this is a night test):
```
{
    "timestamp":{
       "value":"2021-08-16T21:41:27+10:00"
    },
    "status":{
       "Code":0,
       "Reason":"",
       "UserMessage":""
    },
    "meters":{
       "1":{
          "current_ac_phase_1":{
             "value":2.861,
             "unit":"A"
          },
          "energy_reactive_ac_consumed":{
             "value":11776730,
             "unit":"Wh"
          },
          "energy_reactive_ac_produced":{
             "value":76031860,
             "unit":"Wh"
          },
          "energy_real_ac_minus":{
             "value":9843749,
             "unit":"Wh"
          },
          "energy_real_ac_plus":{
             "value":18378303,
             "unit":"Wh"
          },
          "energy_real_consumed":{
             "value":18378303,
             "unit":"Wh"
          },
          "energy_real_produced":{
             "value":9843749,
             "unit":"Wh"
          },
          "frequency_phase_average":{
             "value":50,
             "unit":"Hz"
          },
          "power_apparent_phase_1":{
             "value":694.93,
             "unit":"W"
          },
          "power_apparent":{
             "value":694.93,
             "unit":"W"
          },
          "power_factor_phase_1":{
             "value":0.75,
             "unit":"W"
          },
          "power_factor":{
             "value":0.75,
             "unit":"W"
          },
          "power_reactive_phase_1":{
             "value":-408.54,
             "unit":"W"
          },
          "power_reactive":{
             "value":-408.54,
             "unit":"W"
          },
          "power_real_phase_1":{
             "value":522.08,
             "unit":"W"
          },
          "power_real":{
             "value":522.08,
             "unit":"W"
          },
          "voltage_ac_phase_1":{
             "value":242.9,
             "unit":"V"
          },
          "meter_location":{
             "value":0
          },
          "enable":{
             "value":1
          },
          "visible":{
             "value":1
          },
          "manufacturer":{
             "value":"Fronius"
          },
          "model":{
             "value":"Smart Meter 63A-1"
          },
          "serial":{
             "value":"18032881"
          }
       }
    }
 }
```

But it doesn't iterate the meters object.  `res['meters']['1']` contains all the juicy info.

**Comment by ianleeder** [comment]
Also, that error I'm getting logged about "No data..."?  That comes from the line 
```
sensor["inverter_state"] = {"value": data["DeviceStatus"]["InverterState"]}
```
in the function `_device_inverter_data`.

`data["DeviceStatus"]` does not contain a key called `InverterState`.  This is what `data["DeviceStatus"]` contains:
```
{
   "ErrorCode":307,
   "LEDColor":1,
   "LEDState":0,
   "MgmtTimerRemainingTime":3,
   "StateToReset":false,
   "StatusCode":3
}
```

**Comment by ianleeder** [comment]
So to summarise, I started with this config:
```
    - sensor_type: inverter
      device: 1
    - sensor_type: meter
      scope: system
```
But parsing meter by `scope: system` fails to iterate the meters, and parsing inverter by `device: 1` fails on a missing key in the response (and logs an error every time).  Now my config is reversed!
```
    - sensor_type: inverter
      scope: system
    - sensor_type: meter
      device: 1
```

**Comment by ianleeder** [comment]
Here are the daytime results (cloudy, low production).  And duh.  I just realised you wanted all the DEBUG output too.
```
DEBUG:asyncio:Using selector: KqueueSelector
DEBUG:pyfronius:using highest supported API version API_VERSION.V1
DEBUG:pyfronius:Get current system meter data for GetMeterRealtimeData.cgi?Scope=System
DEBUG:pyfronius:Converting system meter data: '{'1': {'Current_AC_Phase_1': 2.401, 'Current_AC_Sum': 2.401, 'Details': {'Manufacturer': 'Fronius', 'Model': 'Smart Meter 63A-1', 'Serial': '18032881'}, 'Enable': 1, 'EnergyReactive_VArAC_Phase_1_Consumed': 11787960, 'EnergyReactive_VArAC_Phase_1_Produced': 76075790, 'EnergyReactive_VArAC_Sum_Consumed': 11787960, 'EnergyReactive_VArAC_Sum_Produced': 76075790, 'EnergyReal_WAC_Minus_Absolute': 9844050, 'EnergyReal_WAC_Phase_1_Consumed': 18396769, 'EnergyReal_WAC_Phase_1_Produced': 9844050, 'EnergyReal_WAC_Plus_Absolute': 18396769, 'EnergyReal_WAC_Sum_Consumed': 18396769, 'EnergyReal_WAC_Sum_Produced': 9844050, 'Frequency_Phase_Average': 49.9, 'Meter_Location_Current': 0, 'PowerApparent_S_Phase_1': 584.64, 'PowerApparent_S_Sum': 584.64, 'PowerFactor_Phase_1': 0.74, 'PowerFactor_Sum': 0.74, 'PowerReactive_Q_Phase_1': -237.11, 'PowerReactive_Q_Sum': -237.11, 'PowerReal_P_Phase_1': 436.39, 'PowerReal_P_Sum': 436.39, 'TimeStamp': 1629169819, 'Visible': 1, 'Voltage_AC_Phase_1': 243.5}}'
timestamp
status
meters
```

**Comment by nielstron** [comment]
Actually DEBUG info is not so important, its more about the raw returned values :)

**Comment by nielstron** [comment]
Thanks a lot, I will look into it asap!

**Comment by nielstron** [comment]
So as I see it, this is actually not an issue of the pyfronius package after all. The best thing (and it is a long overdue addition) would be to simply detect all available devices in homeassistant and automatically add them. Maybe it would be useful to add some abstraction functions to pyfronius package in order to aid - specifically functions to return all device ids of installed inverters and meters.

**Comment by ianleeder** [comment]
Sounds good to me.  Don't forget about the logging issue though. 
https://github.com/nielstron/pyfronius/blob/246ce1dae624be382905b53514fab4f286c1f52d/pyfronius/__init__.py#L533-L536

Line 534 is throwing an error, and if Python does error handling like any other language I've met, that means it's not returning the data on line 536.

I'm not sure what value `InverterState` is supposed to contain, or I could submit a PR myself, but this is all `DeviceStatus` contains:
```
"DeviceStatus" : {
    "ErrorCode" : 307,
    "LEDColor" : 1,
    "LEDState" : 0,
    "MgmtTimerRemainingTime" : 5,
    "StateToReset" : false,
    "StatusCode" : 3
}
```

Interestingly enough even the test datasets in `/tests/test_structure/v1...` don't contain this `InverterState` value.  Do the tests currently pass?  If I get a chance tomorrow I'll see if I can get the the unit tests running, and see why.

**Comment by nielstron** [comment]
The thing is that `sensor` is not a newly created dictionary but incrementally updated and was passed to the function by reference in the first place. The reason that most values end up in the returned data still is that it is the last value to be queried and all previous values have already been added.

**Comment by ianleeder** [comment]
I _just_ worked out that it was passed by reference, not value.  And since the error occurs on the very last value being added to the dictionary, no data is lost.  So theoretically that function doesn't need to return anything, and this line doesn't need to assign it back to `sensor`:
https://github.com/nielstron/pyfronius/blob/246ce1dae624be382905b53514fab4f286c1f52d/pyfronius/__init__.py#L248

Still, it would be nice to fix this error, so that:
- If anyone ever tries to add new values below this line, they won't get skipped, and
- It doesn't log an error every single call

**Comment by ianleeder** [comment]
I added PR https://github.com/nielstron/pyfronius/pull/34 that fixes my problem.  Not sure on your PR procedure (eg target branch), feel free to hack or reject as you see fit.
