### ISSUE TITLE
Add Storage System scope

### ISSUE THREAD

**Issue by farmio** [nielstron/pyfronius#37]
Storage is only supported with device scope. System scope should save a bunch of requests.

**Comment by nielstron** [comment]
Please provide some sample data returned by your fronius device for the storage call with system scope :)

**Comment by farmio** [comment]
Sorry, I can't. I have no storage in my system. 
I can only point to https://www.fronius.com/~/downloads/Solar%20Energy/Operating%20Instructions/42%2C0410%2C2012.pdf page 53-56

**Comment by nielstron** [comment]
Added experimental support as of https://github.com/nielstron/pyfronius/commit/c29333e9f3d522f0d9889aba7138e05d080bf24b
