### ISSUE TITLE
HA: Individual device entities from System scope

### ISSUE THREAD

**Issue by farmio** [nielstron/pyfronius#44]
Currently no individual device entities are created from system scoped configurations. The data is there, but only cumulative data is used in the HA integration. (Meter has no cumulative data so system scope for meter only creates a timestamp entity). 

We could iterate through the returned individual data (inverters, meters, storages) and create entities as if they were configured with device scope. 

Here only the cumulative values are extracted
https://github.com/home-assistant/core/blob/d277e0fb03a55d2bb733d4bed8b85a023d87e225/homeassistant/components/fronius/sensor.py#L229

**Comment by nielstron** [comment]
That is one possibility. However device scope data tends to be more detailed, so I would prefer to use system scope only for cumulative data or extracting which devices can be addressed individually in device scope.

**Comment by farmio** [comment]
This is true for inverters - on device scope "CommonInverterData" is used. 
Meter and storage don't have a "DataCollection" parameter - their response is the same system or device scoped.

**Comment by nielstron** [comment]
True, for meter and storage this makes sense. Maybe a good first step towards configuration-less HA sensors :)

**Comment by farmio** [comment]
fixed in https://github.com/home-assistant/core/pull/56166
