### ISSUE TITLE
unable to clone

### ISSUE THREAD

**Issue by retos** [nielstron/pyfronius#5]
Not sure if it is releated to my machine, or the content of the project. If I clone I get an error:
![image](https://user-images.githubusercontent.com/4066100/148635182-1668275c-dc10-493a-b0dc-f963fcb4d832.png)
nothing gets cloned. With the suggested git restore I have more:
![image](https://user-images.githubusercontent.com/4066100/148635210-463026b4-8d5e-4cff-8a75-c0aee855c549.png)

**Comment by farmio** [comment]
🤔 seems like Windows can't handle the filenames of the test structures for some reason. Have you tried Linux or WSL2?

**Comment by retos** [comment]
> 🤔 seems like Windows can't handle the filenames of the test structures for some reason. Have you tried Linux or WSL2?

Yes, you are right. I will try on a Linux environment. Might take me a while, but I will get back to you.

**Comment by nielstron** [comment]
The issue is that some filenames contain "?", which usually used to express get parameters. By just having them as filenames the mockup server structure is simplified a lot but it might be worth considering to change that structure.

This is also the reason test files are not included in the package build - otherwise windows users could not run pyfronius.

**Comment by retos** [comment]
Ok, I was able to clone (on a linux machine). But I' don't know where to start. Do I execute the setup.py. And then what? I can see there is a example.py, but I was expecting the need to enter some config somewhere.

**Comment by nielstron** [comment]
You can run the example program like this

`./example.py <ip-of-printer>`

Thanks for the note, this should be added to the README.

**Comment by retos** [comment]
Was able to test it. I can share the output with you if you are interested. I have two inverters, a smartmeter, an ohmpilot and a battery. The ohmpilot is not yet connected. The inverters operate in master/slave configuration. The slave inverter goes offline if not needed. Therefore I was only able to query the master at the moment.
